services:
  - type: web
    name: smart-parking-api
    runtime: python
    rootDir: smart_parking/APPAPI
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --host=0.0.0.0 --port=$PORT appAPI:app
    plan: free
