// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf0HFIlqfg7_jy3kv2VFao9j2P_Yqa3nA',
    appId: '1:588798147451:web:f1059bb3393e9de2f65bde',
    messagingSenderId: '588798147451',
    projectId: 'parkingapp5',
    authDomain: 'parkingapp5.firebaseapp.com',
    storageBucket: 'parkingapp5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxJq0Uuq7y6oBw5KbTpxFo3THEVc5ccG4',
    appId: '1:588798147451:ios:7cf4a3ba8ee07c54f65bde',
    messagingSenderId: '588798147451',
    projectId: 'parkingapp5',
    storageBucket: 'parkingapp5.firebasestorage.app',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxJq0Uuq7y6oBw5KbTpxFo3THEVc5ccG4',
    appId: '1:588798147451:ios:7cf4a3ba8ee07c54f65bde',
    messagingSenderId: '588798147451',
    projectId: 'parkingapp5',
    storageBucket: 'parkingapp5.firebasestorage.app',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf0HFIlqfg7_jy3kv2VFao9j2P_Yqa3nA',
    appId: '1:588798147451:web:f9bc4488712f8727f65bde',
    messagingSenderId: '588798147451',
    projectId: 'parkingapp5',
    authDomain: 'parkingapp5.firebaseapp.com',
    storageBucket: 'parkingapp5.firebasestorage.app',
  );
}
